import { createClient } from "@supabase/supabase-js";
const sb = createClient("https://ckqfiwcixkzkmdxqyxqq.supabase.co", "sb_publishable_iPNkQlWTSlkyCeTC5NFqIg_AYJP_xBV");
const { data: leaderboard } = await sb.from("wc_player_leaderboard").select("*").order("total_points",{ascending:false}).limit(5);
console.log("LB cols:", Object.keys(leaderboard?.[0]??{}));
console.log(JSON.stringify(leaderboard,null,2));
const { data: rs } = await sb.from("wc_round_standings").select("*").limit(2);
console.log("RS:", rs);
const { data: ps } = await sb.from("wc_player_scores").select("*").limit(2);
console.log("PS:", ps);
const { count: tcount } = await sb.from("wc_teams").select("*",{count:"exact",head:true});
console.log("teams count:", tcount);
const { data: tall } = await sb.from("wc_teams").select("*").order("id");
console.log("teams:", tall);
