/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamManagerIdRouteImport } from './routes/team.$managerId'
import { Route as SeasonSeasonIdRouteImport } from './routes/season.$seasonId'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamManagerIdRoute = TeamManagerIdRouteImport.update({
  id: '/team/$managerId',
  path: '/team/$managerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSeasonIdRoute = SeasonSeasonIdRouteImport.update({
  id: '/season/$seasonId',
  path: '/season/$seasonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/records'
    | '/table'
    | '/season/$seasonId'
    | '/team/$managerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/records' | '/table' | '/season/$seasonId' | '/team/$managerId'
  id:
    | '__root__'
    | '/'
    | '/records'
    | '/table'
    | '/season/$seasonId'
    | '/team/$managerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordsRoute: typeof RecordsRoute
  TableRoute: typeof TableRoute
  SeasonSeasonIdRoute: typeof SeasonSeasonIdRoute
  TeamManagerIdRoute: typeof TeamManagerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$managerId': {
      id: '/team/$managerId'
      path: '/team/$managerId'
      fullPath: '/team/$managerId'
      preLoaderRoute: typeof TeamManagerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$seasonId': {
      id: '/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/season/$seasonId'
      preLoaderRoute: typeof SeasonSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordsRoute: RecordsRoute,
  TableRoute: TableRoute,
  SeasonSeasonIdRoute: SeasonSeasonIdRoute,
  TeamManagerIdRoute: TeamManagerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
