/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldCupRouteImport } from './routes/world-cup'
import { Route as TableRouteImport } from './routes/table'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as H2hRouteImport } from './routes/h2h'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldCupManagerIdRouteImport } from './routes/world-cup.$managerId'
import { Route as TeamManagerIdRouteImport } from './routes/team.$managerId'
import { Route as SeasonSeasonIdRouteImport } from './routes/season.$seasonId'
import { Route as RulesScoringRouteImport } from './routes/rules.scoring'
import { Route as RulesPrizePoolRouteImport } from './routes/rules.prize-pool'
import { Route as RulesGeneralRouteImport } from './routes/rules.general'
import { Route as RulesDraftOrderRouteImport } from './routes/rules.draft-order'

const WorldCupRoute = WorldCupRouteImport.update({
  id: '/world-cup',
  path: '/world-cup',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const H2hRoute = H2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCupManagerIdRoute = WorldCupManagerIdRouteImport.update({
  id: '/$managerId',
  path: '/$managerId',
  getParentRoute: () => WorldCupRoute,
} as any)
const TeamManagerIdRoute = TeamManagerIdRouteImport.update({
  id: '/team/$managerId',
  path: '/team/$managerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSeasonIdRoute = SeasonSeasonIdRouteImport.update({
  id: '/season/$seasonId',
  path: '/season/$seasonId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesScoringRoute = RulesScoringRouteImport.update({
  id: '/rules/scoring',
  path: '/rules/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesPrizePoolRoute = RulesPrizePoolRouteImport.update({
  id: '/rules/prize-pool',
  path: '/rules/prize-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesGeneralRoute = RulesGeneralRouteImport.update({
  id: '/rules/general',
  path: '/rules/general',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesDraftOrderRoute = RulesDraftOrderRouteImport.update({
  id: '/rules/draft-order',
  path: '/rules/draft-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/h2h': typeof H2hRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/world-cup': typeof WorldCupRouteWithChildren
  '/rules/draft-order': typeof RulesDraftOrderRoute
  '/rules/general': typeof RulesGeneralRoute
  '/rules/prize-pool': typeof RulesPrizePoolRoute
  '/rules/scoring': typeof RulesScoringRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
  '/world-cup/$managerId': typeof WorldCupManagerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/h2h': typeof H2hRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/world-cup': typeof WorldCupRouteWithChildren
  '/rules/draft-order': typeof RulesDraftOrderRoute
  '/rules/general': typeof RulesGeneralRoute
  '/rules/prize-pool': typeof RulesPrizePoolRoute
  '/rules/scoring': typeof RulesScoringRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
  '/world-cup/$managerId': typeof WorldCupManagerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/h2h': typeof H2hRoute
  '/records': typeof RecordsRoute
  '/table': typeof TableRoute
  '/world-cup': typeof WorldCupRouteWithChildren
  '/rules/draft-order': typeof RulesDraftOrderRoute
  '/rules/general': typeof RulesGeneralRoute
  '/rules/prize-pool': typeof RulesPrizePoolRoute
  '/rules/scoring': typeof RulesScoringRoute
  '/season/$seasonId': typeof SeasonSeasonIdRoute
  '/team/$managerId': typeof TeamManagerIdRoute
  '/world-cup/$managerId': typeof WorldCupManagerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/h2h'
    | '/records'
    | '/table'
    | '/world-cup'
    | '/rules/draft-order'
    | '/rules/general'
    | '/rules/prize-pool'
    | '/rules/scoring'
    | '/season/$seasonId'
    | '/team/$managerId'
    | '/world-cup/$managerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/h2h'
    | '/records'
    | '/table'
    | '/world-cup'
    | '/rules/draft-order'
    | '/rules/general'
    | '/rules/prize-pool'
    | '/rules/scoring'
    | '/season/$seasonId'
    | '/team/$managerId'
    | '/world-cup/$managerId'
  id:
    | '__root__'
    | '/'
    | '/h2h'
    | '/records'
    | '/table'
    | '/world-cup'
    | '/rules/draft-order'
    | '/rules/general'
    | '/rules/prize-pool'
    | '/rules/scoring'
    | '/season/$seasonId'
    | '/team/$managerId'
    | '/world-cup/$managerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  H2hRoute: typeof H2hRoute
  RecordsRoute: typeof RecordsRoute
  TableRoute: typeof TableRoute
  WorldCupRoute: typeof WorldCupRouteWithChildren
  RulesDraftOrderRoute: typeof RulesDraftOrderRoute
  RulesGeneralRoute: typeof RulesGeneralRoute
  RulesPrizePoolRoute: typeof RulesPrizePoolRoute
  RulesScoringRoute: typeof RulesScoringRoute
  SeasonSeasonIdRoute: typeof SeasonSeasonIdRoute
  TeamManagerIdRoute: typeof TeamManagerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world-cup': {
      id: '/world-cup'
      path: '/world-cup'
      fullPath: '/world-cup'
      preLoaderRoute: typeof WorldCupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2h': {
      id: '/h2h'
      path: '/h2h'
      fullPath: '/h2h'
      preLoaderRoute: typeof H2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-cup/$managerId': {
      id: '/world-cup/$managerId'
      path: '/$managerId'
      fullPath: '/world-cup/$managerId'
      preLoaderRoute: typeof WorldCupManagerIdRouteImport
      parentRoute: typeof WorldCupRoute
    }
    '/team/$managerId': {
      id: '/team/$managerId'
      path: '/team/$managerId'
      fullPath: '/team/$managerId'
      preLoaderRoute: typeof TeamManagerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$seasonId': {
      id: '/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/season/$seasonId'
      preLoaderRoute: typeof SeasonSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/scoring': {
      id: '/rules/scoring'
      path: '/rules/scoring'
      fullPath: '/rules/scoring'
      preLoaderRoute: typeof RulesScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/prize-pool': {
      id: '/rules/prize-pool'
      path: '/rules/prize-pool'
      fullPath: '/rules/prize-pool'
      preLoaderRoute: typeof RulesPrizePoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/general': {
      id: '/rules/general'
      path: '/rules/general'
      fullPath: '/rules/general'
      preLoaderRoute: typeof RulesGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/draft-order': {
      id: '/rules/draft-order'
      path: '/rules/draft-order'
      fullPath: '/rules/draft-order'
      preLoaderRoute: typeof RulesDraftOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorldCupRouteChildren {
  WorldCupManagerIdRoute: typeof WorldCupManagerIdRoute
}

const WorldCupRouteChildren: WorldCupRouteChildren = {
  WorldCupManagerIdRoute: WorldCupManagerIdRoute,
}

const WorldCupRouteWithChildren = WorldCupRoute._addFileChildren(
  WorldCupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  H2hRoute: H2hRoute,
  RecordsRoute: RecordsRoute,
  TableRoute: TableRoute,
  WorldCupRoute: WorldCupRouteWithChildren,
  RulesDraftOrderRoute: RulesDraftOrderRoute,
  RulesGeneralRoute: RulesGeneralRoute,
  RulesPrizePoolRoute: RulesPrizePoolRoute,
  RulesScoringRoute: RulesScoringRoute,
  SeasonSeasonIdRoute: SeasonSeasonIdRoute,
  TeamManagerIdRoute: TeamManagerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
